baseurl: http://example.org/
languageCode: en-us
title: Hugrid - Grid Theme For Hugo
theme: hugrid
googleAnalytics: UA-XXXXXXXX-Y
contentdir: content
datadir: data
layoutdir: layouts
publishdir: public
params:
  author: Pavel Kanyshev
  bodybgcolor: '#f9f9f9'
  buttontext: Get the theme
  description: Hugrid - grid theme for Hugo with an expanding image preview.
  footertext: Made by [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/),
    [Hugo](http://gohugo.io) and [me](https://github.com/aerohub)
  keywords: Hugo, Hugo theme, grid theme, portfolio, bookmarks, collection, contacts
  subtitle: A kind of boilerplate to perform anyone or anything quickly. Portfolio,
    collection, bookmarks, contacts and so on.
  title: Hugrid - a simple grid theme for Hugo
